# -*- mode: ruby -*-
# vi: set ft=ruby :

require './vagrant-provision-reboot-plugin'

Vagrant.configure(2) do |config|
  # Windows 7 64 bit Professional SP1
  config.vm.box = "rifung/win7_64"
  config.vm.hostname = "RaPiD" 
  config.vm.provider :virtualbox do |vb| 
  vb.name = "Chowan-vboddul-RaPiD" 
 end 
 
   config.vm.provider "virtualbox" do |vb|
  	# Display the VirtualBox GUI when booting the machine
       vb.gui = true

        #Disable USB 
       vb.customize ["modifyvm", :id, "--usb", "off"] 
       vb.customize ["modifyvm", :id, "--usbehci", "off"] 

  end

  config.vm.communicator = "winrm"

 # for provisioning we need:
  # chocolatey:
  config.vm.provision :shell, path: "scripts/InstallChocolatey.ps1"
  # ...in the path for all users:
  config.vm.provision :shell, inline: '[Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Chocolatey\bin", "Machine")'

  # run the installation scripts

  config.vm.provision :shell, path: "scripts/install-dotnet.bat"

  config.vm.provision :shell, path: "scripts/install-MCR.cmd"
  
  config.vm.provision :windows_reboot  

  config.vm.provision :shell, path: "scripts/install-RaPiD.ps1"

end
